apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itunes-gr-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  # ingressClassName: nginx
  # tls:
  # - hosts:
  #   - homeline.kg
  #   secretName: cbr-tls
  rules:
  - host: nf-100-105.jinr.ru
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: itunes-gr-frontend
            port:
              number: 80
