apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ficuszet@yandex.ru
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-itunes-gr
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    projectcontour.io/response-timeout: infinity
spec:
  tls:
  - hosts:
    - app.itunes-gr.ru
    secretName: tls-secret
    # secretName: letsencrypt-prod
  rules:
    - host: app.itunes-gr.ru
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: itunes-gr-frontend
              port:
                number: 80