---
version: '3'
services:
  backend:
    build: backend
    image: sgoryunov/backend
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - db

  frontend:
    build: frontend
    image: sgoryunov/frontend
    container_name: frontend
    ports:
      - 8080:80
    depends_on:
      - backend
  db:
    image: mariadb:10.7
    restart: always
    container_name: mysql
    environment:
      - MARIADB_ROOT_PASSWORD=DB_ROOT_PASS
      - MYSQL_DATABASE=DB_NAME
      - MYSQL_USER=DB_USER
      - MYSQL_PASSWORD=DB_USER_PASS
     