---
version: '3'
services:
  backend:
    build: backend
    image: sgoryunov/backend
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - db

  frontend:
    build: frontend
    image: sgoryunov/frontend
    container_name: frontend
    ports:
      - 8080:5000
    depends_on:
      - backend
  db:
    image: mariadb:10.7
    restart: always
    container_name: mysql
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
     