---
version: '3'
services:
  backend:
    build: backend
    container_name: backend
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    image: mariadb:10.7
    # restart: always
    container_name: mysql
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    