apiVersion: apps/v1
kind: Deployment
metadata:
  name: itunes-gr-backend
  labels:
    owner : Semyon_Goryunov
spec:
  selector:
    matchLabels:
      app: itunes-gr-backend
  template:
    metadata:
      labels:
        app: itunes-gr-backend
    spec:
      containers:
      - name: itunes-gr-backend
        image: sgoryunov/backend:latest
        livenessProbe:
          httpGet:
           path: /health
           port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        # ports:
        #   - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: database_url
          valueFrom:
            secretKeyRef:
              name: connection-string
              key: DATABASE_URL
      