apiVersion: v1
data:
  DATABASE_URL:  bXlzcWw6Ly9teXVzZXI6bXlwYXNzd29yZEBzZ29yeXVub3YtZGIuY2NrazNveDl6d2l4LmV1LW5vcnRoLTEucmRzLmFtYXpvbmF3cy5jb206MzMwNi9teWRhdGFiYXNlCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: connection-string
