apiVersion: v1
kind: Service
metadata:
  name: itunes-gr-backend
  labels:
     name: itunes-gr-backend
     owner: Semyon_Goryunov
spec:
  selector:
    app: itunes-gr-backend
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 5000  # Port on Load Balancer
