apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbr-backend
  labels:
    owner : Nikolai_Voloshin
spec:
  selector:
    matchLabels:
      app: cbr-backend
  template:
    metadata:
      labels:
        app: cbr-backend
    spec:
      containers:
      - name: cbr-backend
        image: gcr.io/cbr-grabber/cbr-backend-staging:latest
        livenessProbe:
          httpGet:
           path: /healthz
           port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: database_url
          valueFrom:
            secretKeyRef:
              name: database-url
              key: DATABASE_URL
        - name: mysql_user
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: MYSQL_USER
        - name: mysql_password
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: MYSQL_PASSWORD
        - name: mysql_host
          valueFrom:
            secretKeyRef:
              name: mysql-dbhost
              key: MYSQL_DBHOST
        - name: mysql_db
          valueFrom:
            secretKeyRef:
              name: mysql-db
              key: MYSQL_DB

      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"
          - "-instances=cbr-grabber:europe-west3:staging-instance=tcp:3306"
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: sa-key-volume
          mountPath: /secrets/
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu:    "50m"
          limits:
            memory: "256Mi"
            cpu:    "100m"
      volumes:
      - name: sa-key-volume
        secret:
          secretName: sa-key
