apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cbr-backend
  labels:
    name : cbr-backend
    owner : Nikolai_Voloshin
spec:
    scaleTargetRef:
      apiVersion: apps/v2beta1
      kind: Deployment
      name: cbr-backend
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
