apiVersion: v1
kind: Service
metadata:
  name: cbr-backend
  labels:
     name: cbr-backend
     owner: Nikolai_Voloshin
spec:
  selector:
    app: cbr-backend
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 5000  # Port on Load Balancer
