apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cbr-frontend
  labels:
    name : cbr-frontend
    owner : Nikolai_Voloshin
spec:
    scaleTargetRef:
      apiVersion: apps/v2beta1
      kind: Deployment
      name: cbr-frontend
    minReplicas: 1
    maxReplicas: 4
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
