"""empty message

Revision ID: 267fae651421
Revises: f1da374fa14c
Create Date: 2022-04-12 16:38:09.846098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267fae651421'
down_revision = 'f1da374fa14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itunes_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('collectionName', sa.String(length=50), nullable=False),
    sa.Column('trackName', sa.String(length=50), nullable=False),
    sa.Column('collectionPrice', sa.Float(), nullable=True),
    sa.Column('trackPrice', sa.Float(), nullable=True),
    sa.Column('primaryGenreName', sa.String(length=50), nullable=False),
    sa.Column('trackCount', sa.Integer(), nullable=True),
    sa.Column('trackNumber', sa.Integer(), nullable=True),
    sa.Column('releaseDate', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itunes_data')
    # ### end Alembic commands ###
