"""empty message

Revision ID: 3a9dbeb4c307
Revises: 
Create Date: 2022-04-12 14:29:44.618379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9dbeb4c307'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itunes_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('collectionName', sa.String(length=50), nullable=False),
    sa.Column('trackName', sa.String(length=50), nullable=False),
    sa.Column('collectionPrice', sa.Float(), nullable=True),
    sa.Column('trackPrice', sa.Float(), nullable=True),
    sa.Column('primaryGenreName', sa.String(length=50), nullable=False),
    sa.Column('trackCount', sa.Integer(), nullable=True),
    sa.Column('trackNumber', sa.Integer(), nullable=True),
    sa.Column('releaseDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itunes_data')
    # ### end Alembic commands ###
