"""empty message

Revision ID: f1da374fa14c
Revises: 3a9dbeb4c307
Create Date: 2022-04-12 16:34:21.662861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1da374fa14c'
down_revision = '3a9dbeb4c307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itunes_data', 'releaseDate',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itunes_data', 'releaseDate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
